import {it,expect} from 'vitest';
import {createGame} from '../src/core/game';
import {startResolution,resolveChoice} from '../src/core/resolution';
import {specialCard} from '../src/core/cardCatalog';
import {historyEffects} from '../src/core/prelude';
import {cardEffects} from '../src/core/specialCards';
import {effectText} from '../src/core/effectNames';
import type {GameState,SeatId} from '../src/core/types';
function game(seat:SeatId){const s=createGame('timing1511',42,'FULL',true,false,true);s.prelude!.active=false;s.status='PLAYING';s.phase='PLAY';s.activeSeat=s.viewSeat=s.operatorSeat=seat;for(const d of Object.values(s.decks)){d.drawPile.push(...d.hand.splice(0),...d.active.splice(0),...d.faceDown.splice(0));}return s;}
function add(s:GameState,id:string,zone:'hand'|'active'|'faceDown') {const def=specialCard(id,true)!,d=s.decks[def.deckOwner];let c=d.drawPile.find(c=>c.definitionId===id);if(c)d.drawPile=d.drawPile.filter(x=>x.id!==c!.id);else c={id:`test:${id}`,definitionId:id,deckOwner:def.deckOwner,country:def.country,balance:true};d[zone].push(c);return c;}
function reply(s:GameState,ids:string[]=[]){const c=s.resolution!.choice!;expect(c).toBeTruthy();expect(resolveChoice(s,c.seat,c.id,ids)).toBe(true);}
function use(s:GameState,label:string){const c=s.resolution!.choice!;expect(c.options.map(o=>o.label)).toContain(label);reply(s,[c.options.find(o=>o.label===label)!.id]);}
it.each([true,false])('Lion is offered before resource reallocation; accepted=%s',accept=>{const s=game('italy');add(s,'special_226','hand');s.decks.italy.hand.push(...s.decks.italy.drawPile.splice(0,3));s.phase='TURN_START_WINDOW';startResolution(s,'回合开始','italy',[{kind:'signal',tag:'PHASE:TURN_START_WINDOW',label:'回合开始'}],[]);expect(s.resolution!.choice!.options.map(o=>o.label)).toEqual(['一日之狮']);if(accept)use(s,'一日之狮');else reply(s);if(accept){expect(s.basicPlaysRemaining).toBe(2);expect(s.resolution!.choice).toBeNull();}else{expect(s.resolution!.choice!.options.map(o=>o.label)).toEqual(['资源重整']);reply(s);expect(s.resolution!.running).toBe(false);}});
it('Golden Square recruits before Colonial Empire recomputes scoring',()=>{const s=game('italy');s.phase='SCORE';s.units=[];add(s,'special_214','active');add(s,'special_229','hand');startResolution(s,'计分','italy',[{kind:'signal',tag:'PHASE:SCORE',label:'计分开始'}],[]);expect(s.scores.italy).toBe(0);use(s,'黄金广场政变');for(let i=0;s.resolution?.choice&&i<20;i++){const c=s.resolution.choice;reply(s,c.min?[c.options[0].id]:[]);}expect(s.resolution!.running).toBe(false);expect(s.units.some(u=>u.country==='italy'&&u.regionId==='middle_east')).toBe(true);expect(s.scores.italy).toBe(1);});
it.each(['soviet_union','united_kingdom'] as const)('Tito choices remain Soviet controlled when recruiting %s',country=>{const s=game('soviet_union');s.units=[];const card=add(s,'special_66','hand');startResolution(s,'铁托游击队','soviet_union',cardEffects(s,card),[],card.id);const c=s.resolution!.choice!;expect(c.seat).toBe('soviet_union');expect(c.options.map(o=>effectText(o.label))).toEqual(['在巴尔干：征召苏联陆军','在巴尔干：征召英国陆军']);reply(s,[c.options[country==='soviet_union'?0:1].id]);for(let i=0;s.resolution?.choice&&i<10;i++){const q=s.resolution.choice;expect(q.seat).toBe('soviet_union');reply(s,q.min?[q.options[0].id]:[]);}expect(s.units.some(u=>u.country===country&&u.regionId==='balkans')).toBe(true);});
it.each([['prelude_IT-09','italy',1,2],['prelude_IT-08','italy',3,2],['prelude_US-08','united_states',2,0]] as const)('balance %s executes new discard counts and score', (id,seat,n,points)=>{const s=game(seat),card=add(s,id,'hand'),targets=id==='prelude_IT-09'?['united_kingdom','soviet_union','united_states']:id==='prelude_IT-08'?['soviet_union']:['germany','japan','italy'];const before=targets.map(t=>s.prelude!.decks[t as SeatId].drawPile.length);startResolution(s,'历史',seat,historyEffects(s,card),[],card.id);expect(s.resolution!.running).toBe(false);targets.forEach((t,i)=>expect(s.prelude!.decks[t as SeatId].drawPile.length).toBe(before[i]-n));expect(s.scores[seat]).toBe(points);});
it.each([true,false])('Amtorg lets Soviet optionally set discarded armament; accept=%s',accept=>{const s=game('united_states'),card=add(s,'prelude_US-06','hand'),d=s.prelude!.decks.soviet_union;d.discardPile.push(...d.hand.splice(0),...d.drawPile.splice(0));const arm=d.discardPile.find(c=>specialCard(c.definitionId,true)?.type==='军备')!;expect(specialCard(card.definitionId,true)?.name).toBe('阿姆托尔格贸易公司');expect(specialCard(card.definitionId,true)?.tension).toBe(0);expect(specialCard(card.definitionId,false)?.name).toBe('第二次国共合作');startResolution(s,'贸易公司','united_states',historyEffects(s,card),[],card.id);expect(s.resolution!.choice!.seat).toBe('soviet_union');expect(s.resolution!.choice!.options.every(o=>!Object.hasOwn(s.prelude!.installed,o.id))).toBe(true);reply(s,accept?[arm.id]:[]);expect(s.decks.soviet_union.faceDown.some(c=>c.id===arm.id)).toBe(accept);expect(s.resolution!.running).toBe(false);});
it('shared prompt formatter translates map IDs and action/country codes',()=>{expect(effectText('移除eastern_europe陆军后重建')).toBe('移除东欧陆军后重建');expect(effectText('soviet_union recruit_army · sea_central_pacific')).toBe('苏联 征召陆军 · 中太平洋');});

it('experimental Manchukuo recruits only in eastern China',()=>{
 const s=game('japan'),card=add(s,'prelude_JP-19','hand');s.units=[];startResolution(s,'伪满洲国','japan',historyEffects(s,card),[],card.id);
 expect(s.resolution!.choice!.options.map(o=>o.label).join(' ')).toContain('中国东部');expect(s.resolution!.choice!.options.map(o=>o.label).join(' ')).not.toContain('海参崴');reply(s,[s.resolution!.choice!.options[0].id]);expect(s.units.map(u=>u.regionId)).toEqual(['eastern_china']);
});
