import {expect,it} from 'vitest';
import {createGame,transition,SEATS} from '../src/core';
import type {GameState,Command} from '../src/core';
import {cardEffects} from '../src/core/specialCards';
import {responsePreset} from '../src/controller/responsePresets';
import {startResolution} from '../src/core/resolution';
import {validateState} from '../src/controller/saveFormat';
function send(s:GameState,p:Record<string,unknown>){const r=transition(s,{seat:s.operatorSeat,expectedRevision:s.revision,guided:true,...p} as Command);if(!r.ok)throw Error(r.error);return r.state;}
function choose(s:GameState,ids:string[]){return send(s,{type:'RESOLVE_ENGINE_CHOICE',choiceId:s.resolution!.choice!.id,ids});}
function ready(definitionId:string){const s=createGame('guided',1940,'FULL');s.status='PLAYING';s.phase='PLAY';s.round=1;s.setupCompleted=[...SEATS];s.redistributed=true;for(const seat of SEATS){const d=s.decks[seat];d.drawPile.push(...d.hand);d.hand=[];const i=d.drawPile.findIndex(c=>c.definitionId===definitionId);if(i>=0){d.hand.push(...d.drawPile.splice(i,1));s.activeSeat=s.operatorSeat=s.viewSeat=seat;}}return s;}
function play(s:GameState){const c=s.decks[s.activeSeat].hand[0],effects=cardEffects(s,c);return send(s,{type:'PLAY_CARD',cardId:c.id,targetIds:[],effectIndices:effects.map((_,i)=>i)});}
it('all skipped construction restores hand, phase, RNG and score before play',()=>{let s=ready('special_235');const before=structuredClone(s);s=play(s);expect(s.resolution!.choice!.kind).toBe('ACTION');s=choose(s,[]);s=choose(s,[]);expect(s.decks).toEqual(before.decks);expect(s.phase).toBe('PLAY');expect(s.units).toEqual(before.units);expect(s.scores).toEqual(before.scores);expect(s.resolution).toEqual(before.resolution);expect(s.publicLog??[]).toEqual(before.publicLog??[]);expect(s.publicCardIds??[]).toEqual(before.publicCardIds??[]);});
it('first construction commits; later construction may be skipped',()=>{let s=ready('special_235');s=play(s);s=choose(s,[s.resolution!.choice!.options[0].id]);while(s.resolution?.choice?.kind==='ACTION'&&!s.units.some(u=>u.country==='germany'&&u.regionId==='north_africa'))s=choose(s,[s.resolution.choice.options[0].id]);expect(s.units.some(u=>u.country==='germany'&&u.regionId==='north_africa')).toBe(true);s=choose(s,[]);expect(s.decks.germany.hand).toHaveLength(0);expect(Object.values(s.decks).some(d=>d.discardPile.some(c=>c.definitionId==='special_235'))).toBe(true);});
it('automatic invalid effect still consumes the card',()=>{let s=ready('special_235');s.units.push({id:'enemy',country:'united_kingdom',type:'army',regionId:'north_africa'});s=play(s);if(s.resolution?.choice)s=choose(s,[]);expect(Object.values(s.decks).some(d=>d.discardPile.some(c=>c.definitionId==='special_235'))).toBe(true);});
it('a skipped economic effect never opens the British response window',()=>{let s=responsePreset('anti-submarine','guided-economic').state;s=send(s,{type:'PLAY_CARD',cardId:s.decks.germany.hand.find(c=>c.definitionId==='special_168')!.id,targetIds:[],effectIndices:[0,1]});expect(s.resolution!.choice!.kind).toBe('EFFECT_DECISION');s=choose(s,[]);s=choose(s,[]);expect(s.phase).toBe('PLAY');expect(s.decks.united_kingdom.faceDown).toHaveLength(1);});
it('confirming economic effect opens response before it applies',()=>{let s=responsePreset('anti-submarine','guided-response').state;s=send(s,{type:'PLAY_CARD',cardId:s.decks.germany.hand.find(c=>c.definitionId==='special_168')!.id,targetIds:[],effectIndices:[0,1]});s=choose(s,['execute']);expect(s.resolution!.choice!.seat).toBe('united_kingdom');expect(s.viewSeat).toBe('germany');});
it('Democracy selects army or navy by first region, can skip the remainder',()=>{let s=ready('special_98');s=play(s);expect(s.resolution!.choice!.kind).toBe('BUILD_ORDER');s=choose(s,[s.resolution!.choice!.options.find(o=>o.id.startsWith('build_navy|'))!.id]);expect(s.units.some(u=>u.country==='united_kingdom'&&u.type==='navy')).toBe(true);expect(s.resolution!.choice!.kind).toBe('ACTION');s=choose(s,[]);expect(s.decks.united_states.discardPile.some(c=>c.definitionId==='special_98')).toBe(true);});
it('defender declines air defense and keeps its air while army is destroyed',()=>{let s=ready('land_battle');s.units=[{id:'base',country:'united_kingdom',type:'army',regionId:'british_isles'},{id:'a',country:'germany',type:'army',regionId:'germany'},{id:'aa',country:'germany',type:'air',regionId:'germany'},{id:'d',country:'united_kingdom',type:'army',regionId:'western_europe'},{id:'da',country:'united_kingdom',type:'air',regionId:'western_europe'}];s.activeSeat=s.operatorSeat=s.viewSeat='germany';s=play(s);s=choose(s,['western_europe']);expect(s.resolution!.choice!.kind).toBe('AIR_DEFENSE');expect(s.resolution!.choice!.seat).toBe('united_kingdom');s=choose(s,['no']);expect(s.units.some(u=>u.id==='d')).toBe(false);expect(s.units.some(u=>u.id==='da')).toBe(true);});
it.each([true,false])('defense then attacker interception %s has separate owners',intercept=>{
 let s=ready('land_battle');s.activeSeat=s.operatorSeat=s.viewSeat='germany';s.units=[{id:'a',country:'germany',type:'army',regionId:'germany'},{id:'aa',country:'germany',type:'air',regionId:'germany'},{id:'d',country:'united_kingdom',type:'army',regionId:'western_europe'},{id:'da',country:'united_kingdom',type:'air',regionId:'western_europe'}];s=play(s);s=choose(s,['western_europe']);s=choose(s,['yes']);expect(s.resolution!.choice!.kind).toBe('AIR_INTERCEPT');expect(s.resolution!.choice!.seat).toBe('germany');s=choose(s,[intercept?'yes':'no']);expect(s.units.some(u=>u.id==='da')).toBe(false);expect(s.units.some(u=>u.id==='d')).toBe(!intercept);expect(s.units.some(u=>u.id==='aa')).toBe(!intercept);
});
it('Top four ordering is temporary and leaves the rest of the deck intact',()=>{
 let s=ready('special_132');s.decks.germany.active.push(...s.decks.germany.hand);const before=[...s.decks.germany.drawPile];
 startResolution(s,'出牌开始','germany',[{kind:'signal',tag:'PHASE:PLAY',label:'出牌开始'}],[]);
 s=choose(s,[s.resolution!.choice!.options.find(o=>o.label==='卓越规划')!.id]);expect(s.resolution!.choice!.kind).toBe('CARDS');expect(s.resolution!.choice!.options).toHaveLength(4);
 const selected=s.resolution!.choice!.options.map(o=>o.id).reverse();expect(new Set(selected)).toEqual(new Set(before.slice(0,4).map(c=>c.id)));
 s=choose(s,selected);expect(s.decks.germany.drawPile.map(c=>c.id)).toEqual([...selected,...before.slice(4).map(c=>c.id)]);
});
it('an all-skipped restored state stays serializable',()=>{let s=ready('special_235');s=play(s);expect(()=>validateState(JSON.parse(JSON.stringify(s)))).not.toThrow();s=choose(s,[]);s=JSON.parse(JSON.stringify(s));s=choose(s,[]);expect(()=>validateState(s)).not.toThrow();});
it('declining all effects of an optional trigger restores its original window and usage',()=>{
 let s=ready('special_135');const card=s.decks.germany.hand[0];s.decks.germany.active.push(...s.decks.germany.hand);startResolution(s,'时点','germany',[{kind:'trace',label:'时点'}],[{id:'two',label:'两个行动',sourceInstanceId:card.id,owner:'germany',timing:'After',on:'时点',mandatory:false,source:'active',effects:[{kind:'action',country:'germany',action:'build_army',label:'建设陆军'},{kind:'action',country:'germany',action:'build_navy',label:'建设海军'}]}]);
 const before=structuredClone(s);s=choose(s,[s.resolution!.choice!.options[0].id]);s=choose(s,[]);s=choose(s,[]);expect(s.resolution!.choice).toEqual(before.resolution!.choice);expect(s.resolution!.turnUses).toEqual(before.resolution!.turnUses);expect(s.decks).toEqual(before.decks);
});
it('mandatory trigger effects cannot be manually skipped',()=>{let s=ready('special_135');const card=s.decks.germany.hand[0];s.decks.germany.active.push(...s.decks.germany.hand);startResolution(s,'必发','germany',[{kind:'trace',label:'必发'}],[{id:'must',label:'必须建设',sourceInstanceId:card.id,owner:'germany',timing:'After',on:'必发',mandatory:true,source:'active',effects:[{kind:'action',country:'germany',action:'build_army',label:'建设陆军'}]}],undefined,'discardPile',true);expect(s.resolution!.choice!.canSkip).toBe(false);expect(transition(s,{type:'RESOLVE_ENGINE_CHOICE',seat:s.operatorSeat,expectedRevision:s.revision,guided:true,choiceId:s.resolution!.choice!.id,ids:[]}).ok).toBe(false);});
