import {createGame} from '../src/core/game';
import {normalize,makeHeader,localControllers,scope,noCause} from '../src/matchLog/normalize';
import type {Header,Start,Frame,Seat,ResourceConfig} from '../src/matchLog/contract';
export function constructedPool(mode:'A'|'B'):(Header|Start|Frame)[]{
 const native=createGame('constructed-contract-'+mode,7,'BASIC_DEBUG');
 const state=normalize(native),seats=Object.keys(state.controllers) as Seat[];
 state.gameStatus='playing';state.round=1;state.phase='PLAY';state.pendingDecisions=[];state.prelude=null;state.neutrality=null;state.reserves.italy.army=4;
 const keep=new Set(['build_army','build_navy','land_battle','sea_battle']);
 for(const [id,c] of Object.entries(state.cards))if(!keep.has(c.definitionId))delete state.cards[id];
 state.areas=seats.flatMap(seat=>[{areaId:seat+'/resource_pool',seat,kind:'resource_pool' as const,ordered:false,cardIds:Object.values(state.cards).filter(c=>c.deckOwner===seat).map(c=>c.instanceId),displayOrder:null},{areaId:seat+'/resource_discard',seat,kind:'resource_discard' as const,ordered:false,cardIds:[],displayOrder:null}]);
 if(mode==='B')for(const seat of seats){const pool=state.areas.find(a=>a.areaId===seat+'/resource_pool')!,discard=state.areas.find(a=>a.areaId===seat+'/resource_discard')!;const caps:Record<string,number>={build_army:3,build_navy:2,land_battle:1,sea_battle:0};pool.cardIds=pool.cardIds.filter(id=>{if(caps[state.cards[id].definitionId]-->0)return true;discard.cardIds.push(id);return false;});}
 state.availability=Object.fromEntries(seats.map(seat=>{const ids=state.areas.find(a=>a.seat===seat&&a.kind==='resource_pool')!.cardIds,open=mode==='A'?ids:ids.filter(id=>state.cards[id].definitionId==='build_army');return [seat,{cycleId:seat+'/initial',refreshAt:1,openInstanceIds:[...open],remainingCount:ids.length,openCount:open.length}];})) as typeof state.availability;
 for(const [who,k]of Object.entries({public:state.knowledge.public,...state.knowledge.seats})){k.decisions=[];k.visibleDecisionIds=[];k.visibleEffectIds=[];k.areas=state.areas.map(a=>({areaId:a.areaId,visibleCount:a.cardIds.length,knownCards:a.seat===who?a.cardIds.map(id=>({instanceId:id,definitionId:state.cards[id].definitionId})):[],knownOrder:null,knownTopPrefix:[],visibleTypeCounts:{}}));k.knownOpenInstanceIds=who==='public'?{}:{[who]:[...state.availability![who as Seat].openInstanceIds]};}
 const header=makeHeader(native,[state],'snapshot','constructed-'+mode,localControllers(),[{controllerId:'local',kind:'system',displayName:'构造契约样例生成器'}],'constructed');
 header.origin.description='明确标记：构造的契约接口样例，不是真实训练端输出；不证明 A/B 训练规则执行正确';header.gameVersion='foreign-training-baseline';header.mode='resource_pool';header.producer={name:'constructed-contract-fixture',version:'test-1',buildFingerprint:'constructed'};header.compatibility={policy:'declared_schema',requiredFeatures:['qm.fact_state.v1','qm.knowledge.v1','qm.resource_pool_areas.v1']};header.seed=null;
 const composition=(header.resourceConfig as Extract<ResourceConfig,{mode:'standard'}>).deckComposition;
 const policy=(kind:string,parameters:any)=>({kind,version:'1',parameters});
 header.resourceConfig={mode:'resource_pool',courseId:'constructed-interface',courseVersion:'1',cardSet:'basics',availabilityMode:mode,composition,whitelist:header.catalog.map(c=>c.catalogEntryId),openingPolicy:mode==='A'?policy('stage1.open_all',{}):policy('stage1.open_sampled',{nonBasicFraction:0.6,nonBasicMinimum:6,rounding:'ceil',capAtRemaining:true,sampleBy:'instance',replacement:false,basicProbabilities:[{minimumCount:4,probability:1},{minimumCount:3,probability:0.9},{minimumCount:2,probability:0.7},{minimumCount:1,probability:0.4},{minimumCount:0,probability:0}],independentPerBasicType:true,openAllInstancesOnBasicSuccess:true}),refreshPolicy:policy('stage1.refresh',{initializeAllSeats:true,skipFirstOwnTurn:true,refreshAt:'own_turn_start_before_choices',refreshOnExtraPlay:false,refreshOnObserveOrRestore:false,refreshOnCountChange:false}),paymentPolicy:policy('stage1.random_payment',{source:'remaining_pool_including_closed',replacement:false,excludeResolvingAndInstalled:true,constrainedCosts:'eligible_instances',activeHandCostRequiresFull:true}),shortfallPolicy:policy('constructed.shortfall',{forcedDiscard:'discard_remaining_no_penalty',deckShortfall:'lose_one_point_per_missing'}),overrides:[]};
 const start:Start={recordType:'start',seq:1,timelineId:'constructed-'+mode,state};
 const next=structuredClone(state),pool=next.areas.find(a=>a.areaId==='germany/resource_pool')!,id=pool.cardIds.at(-1)!;pool.cardIds.pop();next.areas.find(a=>a.areaId==='germany/resource_discard')!.cardIds.push(id);const v=next.availability!.germany;v.openInstanceIds=v.openInstanceIds.filter(x=>x!==id);v.openCount=v.openInstanceIds.length;v.remainingCount--;
 for(const [who,k]of Object.entries({public:next.knowledge.public,...next.knowledge.seats})){for(const a of k.areas){const actual=next.areas.find(v=>v.areaId===a.areaId)!;a.visibleCount=actual.cardIds.length;a.knownCards=actual.seat===who?actual.cardIds.map(instanceId=>({instanceId,definitionId:next.cards[instanceId].definitionId})):[];}if(who==='germany')k.knownOpenInstanceIds.germany=[...v.openInstanceIds];}
 const frame:Frame={recordType:'frame',kind:'automatic',automationReason:'constructed_random_payment_result',seq:2,beforeStateSeq:1,timelineId:start.timelineId,cause:noCause(),events:[{eventId:'payment',eventType:'cost_paid',actorSeat:'germany',sourceSeat:'germany',entities:[{kind:'card',id}],cause:noCause(),visibility:scope('germany'),outcome:'occurred',before:null,after:null,details:{actualPaidIds:[id],constructed:true},text:'构造样例：资源支付结果'}],state:next};
 return [header,start,frame];
}
