import {it,expect} from 'vitest';
import {startOnline,parseTunnelOutput} from '../scripts/start-online.mjs';
import {mkdtemp,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createServer} from 'node:net';
async function fixture(source){const root=await mkdtemp(join(tmpdir(),'qm-online-'));const file=join(root,'cloud.mjs');await writeFile(file,source);const game=join(root,'game.mjs');await writeFile(game,"console.log('本机入口：http://127.0.0.1:4197/');setInterval(()=>{},1000)");return{root,cloudCommand:[process.execPath,file],gameCommand:[process.execPath,game],port:4197,timeoutMs:1500,log:()=>{},openBrowser:()=>{}};}
it('requires both a URL and a registered connection before starting the game',async()=>{const f=await fixture("console.log('https://some-test.trycloudflare.com');setTimeout(()=>console.log('Registered tunnel connection connIndex=0'),150);setInterval(()=>{},1000)");const urls=[];const started=Date.now();const run=await startOnline({...f,openBrowser:u=>urls.push(u)});expect(Date.now()-started).toBeGreaterThanOrEqual(150);expect(urls).toEqual(['http://127.0.0.1:4197/']);run.stop();await run.closed;});
it('fails when a URL is printed without an established connection',async()=>{const f=await fixture("console.log('https://some-test.trycloudflare.com');setInterval(()=>{},1000)");await expect(startOnline({...f,timeoutMs:200})).rejects.toThrow('超时');});
it('reports early tunnel exit and refuses an occupied game port',async()=>{const f=await fixture('process.exit(1)');await expect(startOnline(f)).rejects.toThrow('退出');const server=createServer();await new Promise(ok=>server.listen(4197,'127.0.0.1',ok));try{await expect(startOnline(f)).rejects.toThrow('占用');}finally{await new Promise(ok=>server.close(ok));}});
it('can cancel while the tunnel is still starting',async()=>{const f=await fixture('setInterval(()=>{},1000)'),controller=new AbortController();const pending=startOnline({...f,signal:controller.signal});setTimeout(()=>controller.abort(),100);await expect(pending).rejects.toThrow('取消');});
it('accepts only the temporary HTTPS hostname from tunnel output',()=>{expect(parseTunnelOutput('https://evil.test/')).toEqual({origin:undefined,connected:false});expect(parseTunnelOutput('https://one-two.trycloudflare.com\nRegistered tunnel connection')).toEqual({origin:'https://one-two.trycloudflare.com',connected:true});});
it('reports missing cloudflared and stops the tunnel if the game exits',async()=>{const f=await fixture("console.log('https://some-test.trycloudflare.com');console.log('Registered tunnel connection');setInterval(()=>{},1000)");await expect(startOnline({...f,cloudCommand:undefined})).rejects.toThrow('找不到');await writeFile(f.gameCommand[1],"console.log('本机入口：http://127.0.0.1:4197/');setTimeout(()=>process.exit(2),100)");const running=await startOnline(f);expect((await running.closed).message).toContain('退出');});
