import artImages from '../data/card-art.json';
import {MAP} from '../core/map';
import {useEffect,useMemo,useState} from 'react';
import type {MatchArchive} from './codec';
import type {Seat,CardInstance} from './contract';
import {replayNode,visibleFrameLabel} from './view';
import type {Perspective} from './view';
import './replay.css';
const names:Record<string,string>={germany:'德国',united_kingdom:'英国',japan:'日本',soviet_union:'苏联',italy:'意大利',united_states:'美国',france:'法国',china:'中国'};
const colors:Record<string,string>={germany:'#777',united_kingdom:'#ac8500',japan:'#555',soviet_union:'#bd1717',italy:'#8043a1',united_states:'#447ccd',france:'#239941',china:'#cc6833'};
const seats=Object.keys(names).slice(0,6) as Seat[];
const phases:Record<string,string>={PRELUDE:'序章',SETUP:'起手选择',TURN_START_WINDOW:'回合开始',PLAY:'出牌',AIR:'空军',SUPPLY:'补给',SCORE:'计分',DISCARD:'弃牌',DRAW:'摸牌'};
const zones:Record<string,string>={regular_hand:'手牌',regular_deck:'牌库',regular_discard:'弃牌堆',prelude_hand:'序章手牌',prelude_deck:'序章牌库',prelude_discard:'序章弃牌堆',resource_pool:'资源池',resource_discard:'弃置/消耗',active:'状态 / 条约',face_down_response:'暗置响应',face_down_armament:'暗置军备',resolving:'结算中',removed:'移出游戏'};
export function MatchReplay({archive:a,onExit}:{archive:MatchArchive;onExit:()=>void}){
 const [seq,setSeq]=useState(1),[before,setBefore]=useState(true),[p,setP]=useState<Perspective>('omniscient'),[seat,setSeat]=useState<Seat>('germany'),[auto,setAuto]=useState(false),[showAuto,setShowAuto]=useState(true),[unit,setUnit]=useState<'step'|'decision'|'turn'|'round'>('step'),[focus,setFocus]=useState<CardInstance|null>(null);
 const node=useMemo(()=>replayNode(a,seq,before,p),[a,seq,before,p]),s=node.state;
 const nodes=[a.start,...a.frames],select=(n:number)=>{setSeq(n);setBefore(true);setFocus(null);};
 const seek=(direction:number)=>{let next=seq+direction;while(next>=1&&next<nodes.length+1){const n=nodes[next-1];if(unit==='step'||unit==='decision'&&n.recordType==='frame'&&'action'in n||unit==='turn'&&n.state.completedCountryTurns!==s.completedCountryTurns||unit==='round'&&n.state.round!==s.round){select(next);return;}next+=direction;}setAuto(false);};
 useEffect(()=>{if(!auto)return;const t=setTimeout(()=>seek(1),1200);return()=>clearTimeout(t);},[auto,seq,unit,p,before]);
 const catalog=new Map(a.header.catalog.map(c=>[c.catalogEntryId,c]));
 const displayCard=(id:string)=>{const c=s.cards[id],d=c&&catalog.get(c.effectiveDefinitionRef);return d&&c?<button className="fact-card" key={id} onClick={()=>setFocus(c)} style={{borderColor:colors[c.printedCountry]}}>{d.art&&Object.values(artImages).includes(d.art.assetId)&&<img alt="" src={d.art.assetId} onError={e=>{e.currentTarget.style.display='none';}} style={{width:'100%'}}/>}<strong>{d.name}</strong><small>{names[c.printedCountry]} · {d.cardType}</small><span>{d.text}</span></button>:null;};
 const finalDecision=node.action?(node.state.pendingDecisions.find(d=>d.decisionId===node.action!.decisionId)??replayNode(a,seq,true,p).state.pendingDecisions.find(d=>d.decisionId===node.action!.decisionId)):null;
 return <main className="fact-replay" data-testid="fact-replay"><header><strong>事实回放 · 只读</strong><span>{a.end.recordingStatus==='partial'?'截至此处 · 非完整终局':'对局已结束'} · 完整性校验通过 · 未执行规则复算</span><button onClick={onExit}>退出回放，返回对局</button></header>
 <nav><select aria-label="回放视角" value={p} onChange={e=>{setP(e.target.value as Perspective);setFocus(null);}}><option value="omniscient">全知</option><option value="public">公共</option>{seats.map(seat=><option key={seat} value={seat}>{names[seat]}视角</option>)}</select><select aria-label="定位单位" value={unit} onChange={e=>setUnit(e.target.value as typeof unit)}><option value="step">子效果</option><option value="decision">决策</option><option value="turn">国家回合</option><option value="round">轮次</option></select><button onClick={()=>select(1)}>起点</button><button disabled={seq===1} onClick={()=>seek(-1)}>后退</button><button disabled={seq===nodes.length} onClick={()=>seek(1)}>前进</button><button onClick={()=>setAuto(v=>!v)}>{auto?'暂停':'自动播放'}</button><label>节点 <input aria-label="跳至节点" type="number" min={1} max={nodes.length} value={seq} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=1&&n<=nodes.length)select(n);}}/></label><span>当前快照 #{node.stateSeq} · 第{s.round}轮 · {names[s.activeSeat]} · {phases[s.phase]??s.phase}</span></nav>
 <div className="fact-layout"><section className="fact-scene"><h2>轴心国 {s.scores.byAlliance.axis}　同盟国 {s.scores.byAlliance.allies}</h2>
 <svg viewBox="0 0 1100 650" role="img" aria-label="回放地图"><rect width="1100" height="650" fill="#dce8e6"/>{a.header.map.artAssetId==='qm-map/'+MAP.sourceSha256&&<image href="/assets/final-map.png" width="1100" height="650" preserveAspectRatio="none"/>}{a.header.map.regions.map((r,i)=>{const x=(r.displayPosition?.x??(i%8)/8)*1100,y=(r.displayPosition?.y??Math.floor(i/8)/7)*650;const units=s.units.filter(u=>u.regionId===r.regionId);return <g key={r.regionId}><rect x={x-40} y={y-20} width={86} height={50} rx={6} fill={a.header.map.artAssetId==='qm-map/'+MAP.sourceSha256?'#f9f5e3b0':r.terrain==='SEA'?'#bbd7e1':'#e5dfb6'} stroke="#657776"/><text x={x} y={y-3} textAnchor="middle" fontSize={11}>{r.name}</text>{units.map((u,k)=><g key={u.unitId}><circle cx={x-25+k*19} cy={y+15} r={9} fill={colors[u.country]} stroke={u.supplied?'#fff':'#000'}/><text x={x-25+k*19} y={y+19} fill="white" fontSize={10} textAnchor="middle">{{army:'陆',navy:'海',air:'空'}[u.type]}</text><title>{names[u.country]} · {u.supplied?'有补给':'无补给'} · {u.unitId}</title></g>)}</g>;})}</svg>
 <p>文件地图布局 · 单位/补给均取自当前快照</p>
 {s.prelude&&<p>序章：{s.prelude.active?'进行中':'已结束'} · 紧张度 {s.prelude.tension} · 序章第{s.prelude.round}轮</p>}{s.neutrality&&<p>美国：{s.neutrality.united_states.neutral?'中立':'已参战'}；苏联：{s.neutrality.soviet_union.neutral?'中立':'已参战'}</p>}
 <section className="fact-decision"><h3>历史问题与最终选择</h3>{node.action&&<><button aria-pressed={before} onClick={()=>setBefore(true)}>选择前</button><button aria-pressed={!before} onClick={()=>setBefore(false)}>选择后</button><p>最终选择：{node.action.disposition==='submit'?node.action.optionIdsOrdered.map(id=>finalDecision?.options.find(o=>o.optionId===id)?.label??'提交').join('、')||'提交':({skip:'跳过',decline:'拒绝响应',cancel:'取消'}[node.action.disposition])}</p></>}{(finalDecision?[finalDecision,...s.pendingDecisions.filter(d=>d.decisionId!==finalDecision.decisionId)]:s.pendingDecisions).map(d=><details key={d.decisionId} open={d.decisionId===finalDecision?.decisionId||d.decisionSeat===seat}><summary>{names[d.decisionSeat]}：{d.prompt}</summary><p>选择 {d.constraints.min}～{d.constraints.max} 项{d.constraints.ordered?'，顺序有效':''}；来源：{d.sourceSeat?names[d.sourceSeat]:'系统'}；部队：{d.unitCountry?names[d.unitCountry]:'无'}</p><ul>{d.options.map(o=><li key={o.optionId}>{o.label} {o.entities.map(ref=><button key={ref.kind+ref.id} onClick={()=>{if(ref.kind==='card')setFocus(s.cards[ref.id]??null);}}>{ref.kind==='card'?catalog.get(s.cards[ref.id]?.effectiveDefinitionRef)?.name??'卡牌':ref.kind==='region'?a.header.map.regions.find(r=>r.regionId===ref.id)?.name??'地区':ref.id}</button>)}</li>)}</ul><details><summary>触发原因、限制与结构化事实</summary><pre>{JSON.stringify({trigger:d.triggerContext,cause:d.cause,constraints:d.constraints},null,2)}</pre></details></details>)}{!finalDecision&&!s.pendingDecisions.length&&<p>此视角没有可见的历史询问。</p>}{node.action?.selection&&<details><summary>实际提交的目标与参数</summary><pre>{JSON.stringify(node.action.selection,null,2)}</pre></details>}{node.events.map(e=><details key={e.eventId}><summary>{e.text}</summary><pre>{JSON.stringify({entities:e.entities,cause:e.cause,outcome:e.outcome,details:e.details},null,2)}</pre></details>)}{node.random&&<details open><summary>记录的随机结果（不重新抽取）</summary><pre>{JSON.stringify(node.random,null,2)}</pre></details>}{s.notifications.map(n=><details key={n.notificationId}><summary>{n.title}</summary>{n.text}</details>)}</section>
 <h3>{names[seat]} · 分数 {s.scores.bySeat[seat]}</h3><p>兵模储备：陆军{s.reserves[seat].army} / 海军{s.reserves[seat].navy} / 空军{s.reserves[seat].air}</p>
 {s.areas.filter(v=>v.seat===seat).map(area=>{const known=node.knowledge?.areas.find(v=>v.areaId===area.areaId),count=known?known.visibleCount:area.cardIds.length;return <details key={area.areaId} open><summary>{zones[area.kind]} · {count??'未知'}{area.ordered?' · 顶→底 / 记录顺序':' · 排序不可见'}</summary><div className="fact-cards">{area.cardIds.map(displayCard)}{count!==null&&count!==undefined&&count>area.cardIds.length&&<span>{count-area.cardIds.length} 张身份未知</span>}</div>{a.header.mode==='resource_pool'&&area.kind==='resource_pool'&&<><h4>本周期可用</h4><div className="fact-cards">{(s.availability?.[seat].openInstanceIds??[]).map(displayCard)}</div><h4>未开放</h4><div className="fact-cards">{(p==='omniscient'||node.knowledge?.knownOpenInstanceIds[seat])?area.cardIds.filter(id=>!s.availability?.[seat].openInstanceIds.includes(id)).map(displayCard):'此视角不可见开放集合'}</div></>}</details>;})}
 {(seat==='united_kingdom'||seat==='united_states'||seat==='soviet_union')&&<p>{seat==='united_kingdom'?'法国':'中国'}兵模储备：{JSON.stringify(s.reserves[seat==='united_kingdom'?'france':'china'])}</p>}<details><summary>地区控制、大本营与补给点</summary>{s.regions.map(r=><p key={r.regionId}>{a.header.map.regions.find(v=>v.regionId===r.regionId)?.name} · 控制：{r.controllers.map(c=>names[c]).join('、')||'无'} · 大本营：{r.effectiveHomeFor.map(c=>names[c]).join('、')||'无'} · 补给：{r.effectiveSupplyFor.join('、')||'无'}</p>)}</details>
 <details><summary>完整结算栈与剩余子效果</summary>{s.resolution.frames.map(f=><details key={f.frameId}><summary>{f.sourceSeat?names[f.sourceSeat]:'系统'} · {f.frameId}</summary>{f.effectsOrdered.map(e=><details key={e.effectId}><summary>{e.kind} · {e.outcome}</summary><pre>{JSON.stringify(e.definition,null,2)}</pre></details>)}</details>)}</details><details><summary>规则配置、课程覆盖与版本</summary><pre>{JSON.stringify({gameVersion:a.header.gameVersion,producer:a.header.producer,rules:a.header.rules,resources:a.header.resourceConfig},null,2)}</pre></details>
 </section><aside className="fact-record"><h2>详细对局记录</h2><div className="fact-record-body"><nav>{seats.map(v=><button key={v} style={{color:colors[v]}} onClick={()=>{setSeat(v);setFocus(null);}}>{names[v]}<small style={{display:'block'}}>分数 {s.scores.bySeat[v]}</small></button>)}</nav><div><label><input type="checkbox" checked={showAuto} onChange={e=>setShowAuto(e.target.checked)}/>展开自动步骤</label>{nodes.filter(n=>showAuto||n.recordType==='start'||n.kind!=='automatic'||'action'in n).map(n=><button className="fact-entry" key={n.seq} aria-current={seq===n.seq?'step':undefined} onClick={()=>select(n.seq)}><small>#{n.seq} · 第{n.state.round}轮 · {names[n.state.activeSeat]}</small>{n.recordType==='start'?'记录起点':visibleFrameLabel(n,a.header,p)}</button>)}</div></div></aside></div>
 {focus&&s.cards[focus.instanceId]&&<dialog open className="fact-index"><button onClick={()=>setFocus(null)}>关闭</button><h3>{catalog.get(focus.effectiveDefinitionRef)?.name}</h3><p>{catalog.get(focus.effectiveDefinitionRef)?.text}</p><p>牌面国家：{names[focus.printedCountry]}；资源所属：{names[focus.deckOwner]}</p><small>{focus.instanceId}</small></dialog>}
 </main>;
}
