import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
const { chromium } = await import(pathToFileURL(join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright-core/index.mjs')).href);
import assert from 'node:assert/strict';
import { mkdir,writeFile } from 'node:fs/promises';
const out='outputs/v2-map-review';await mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const page=await browser.newPage({viewport:{width:1920,height:1080}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
 await page.goto(process.argv[2]??'http://127.0.0.1:5173/');await page.getByRole('button',{name:'中心视图',exact:true}).waitFor();
 assert.equal(await page.locator('.page-heading').count(),0);
 assert.equal(await page.getByRole('button',{name:'欧洲视图',exact:true}).count(),0);
 assert.equal(await page.getByRole('button',{name:'兵模示意',exact:true}).count(),0);
 const newButton=await page.getByRole('button',{name:'新建对局',exact:true}).boundingBox();
 assert(Math.abs(newButton.x+newButton.width/2-960)<2);
 const view=page.locator('.map-viewport'),sheet=page.locator('.map-sheet');
 const box=await view.boundingBox();assert(box.height>800);assert(Math.abs(box.y+box.height-1072)<3);
 await page.getByRole('button',{name:'边界显示',exact:true}).click();assert.equal(await page.locator('.show-boundaries').count(),1);
 await page.getByRole('button',{name:'边界显示',exact:true}).click();
 for(let i=0;i<5;i++)await page.getByRole('button',{name:'缩小地图',exact:true}).click();
 assert.equal(await view.getAttribute('data-zoom'),'50');
 assert.equal(await view.evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(0, 0, 0)');
 const fifty=await sheet.boundingBox();assert(Math.abs(fifty.width-box.width/2)<2);
 assert(Math.abs(fifty.x+fifty.width/2-(box.x+box.width/2))<2);
 await page.mouse.move(box.x+20,box.y+20);await page.mouse.down({button:'right'});await page.mouse.move(box.x+150,box.y+120,{steps:10});await page.mouse.up({button:'right'});
 assert.deepEqual(await sheet.boundingBox(),fifty);assert.equal(await page.getByRole('dialog',{name:'地区详情'}).count(),0);
 await page.screenshot({path:out+'/50-percent.png'});
 for(let i=6;i<=20;i++){await page.getByRole('button',{name:'放大地图',exact:true}).click();assert.equal(await view.getAttribute('data-zoom'),String(i*10));}
 assert(await page.getByRole('button',{name:'放大地图',exact:true}).isDisabled());
 await page.getByRole('button',{name:'中心视图',exact:true}).click();assert.equal(await view.getAttribute('data-zoom'),'100');
 const home=await sheet.boundingBox();
 const germany=page.locator('[data-region-id="germany"]').first();
 await germany.click({button:'right'});await page.getByRole('dialog',{name:'地区详情'}).waitFor();
 assert.equal(await germany.getAttribute('aria-pressed'),'true');
 await page.getByRole('button',{name:'关闭地区详情'}).click();
 await germany.click({button:'right'});await page.getByRole('dialog',{name:'地区详情'}).waitFor();
 assert.equal(await germany.getAttribute('aria-pressed'),'false');
 await page.getByRole('button',{name:'关闭地区详情'}).click();
 const g=await germany.boundingBox();const x=g.x+g.width/2,y=g.y+g.height/2;
 await page.mouse.move(x,y);await page.mouse.down({button:'right'});await page.mouse.move(x+120,y+90,{steps:12});await page.mouse.up({button:'right'});
 assert.equal(await page.getByRole('dialog',{name:'地区详情'}).count(),0);
 assert.equal(await germany.getAttribute('aria-pressed'),'false');
 const panned=await sheet.boundingBox();assert(Math.abs(panned.x-home.x-120)<2);assert(Math.abs(panned.y-home.y-90)<2);
 await page.getByRole('button',{name:'中心视图',exact:true}).click();assert.deepEqual(await sheet.boundingBox(),home);
 await germany.click();assert.equal(await germany.getAttribute('aria-pressed'),'true');await germany.click();assert.equal(await germany.getAttribute('aria-pressed'),'false');
 await page.screenshot({path:out+'/center-view.png'});
 await page.getByRole('button',{name:'新建对局',exact:true}).click();await page.locator('#new-game-form').waitFor({state:'visible'});
 await page.getByRole('button',{name:'创建新游戏 →',exact:true}).click();
 await page.getByRole('heading',{name:/德国手牌/}).waitFor();
 await page.evaluate(()=>window.scrollTo(0,0));
 assert.equal(await page.locator('.map-scoreboard').count(),1);
 const playing=await view.boundingBox();assert(playing.height>800);
 await page.screenshot({path:out+'/playing-view.png'});
 await page.setViewportSize({width:1000,height:800});await page.waitForTimeout(100);await page.evaluate(()=>window.scrollTo(0,0));
 const small=await view.boundingBox();assert(small.height>=320);
 assert.deepEqual(errors,[]);
 await writeFile(out+'/verification.json',JSON.stringify({passed:true,checks:['top banner removed','new game centered','viewport fills available height','only requested controls','all 16 zoom levels','50% centered and immovable with black margin','right click details','right drag without details','center reset','left click toggles','new game form','resize'],errors},null,2));
 console.log('Map UI verification passed');
}finally{await browser.close();}
